#!/usr/bin/env bash
# Installs ufw and sets up the firewall to block all incoming traffic except for TCP ports 22, 443 and 80.
apt-get install ufw
ufw disable
ufw default deny incoming
ufw allow ssh
ufw allow https
ufw allow http
ufw enable
