#!/usr/bin/env bash
# Configures nginx to run as nginx user and have it listen to all active IPs on port 8080.
service nginx stop
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
