#!/usr/bin/env bash
# Configures nginx to run as nginx user and have it listen to all active IPs on port 8080.
sudo service nginx stop
sudo useradd -s /bin/false nginx > /dev/null 2>&1
sudo sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
