#!/usr/bin/env bash
# Does same funtion as previous script (1-run_nginx_as_nginx) in seven lines or less.
service nginx stop
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
